- hosts: all # Alias de grupo o de servidor
# Opciones de conexión
  remote_user: root
# Tareas
  tasks:
   - name: nano remove
     apt: name=nano state=absent
     # MODULO:
        # Propiedades del módulo
   - name: vim install
     apt: name=vim state=present   
   - name: nginx install
     apt: name=nginx state=present
   - name: curl install
     apt: name=curl state=present
     
     
     
     
# Etapa 1
# Iventario- 3 máquinas en 1 grupo, mediante rangos numericos.
#
     